services:
  backend:
    image: shahzaman219/ecommerce-backend:latest
    container_name: ecommerce-backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=ecommerce
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - JWT_SECRET=your_jwt_secret
      - AWS_REGION=us-east-1
      - S3_BUCKET_NAME=ecommerce-product-images-shah
      - NODE_ENV=production
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - ecommerce-network

  frontend:
    image: shahzaman219/ecommerce-frontend:latest
    container_name: ecommerce-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - ecommerce-network

  mysql:
    image: mysql:8.0
    container_name: ecommerce-mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=ecommerce
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./backend/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ecommerce-network

volumes:
  mysql-data:

networks:
  ecommerce-network:
    driver: bridge